### ISSUE TITLE
Missing start_time and duration if EventData not found

### ISSUE THREAD

**Issue by grimbough** [grimbough/IONiseR#2]
More recent fast5 files don't seem to include the EventDetection group any more.  We were extracting the start time and duration of the sequcing run from this, and so many of the downstream plotting functions no longer work.

**Comment by grimbough** [comment]
Commit [df68aac](https://github.com/grimbough/IONiseR/commit/df68aace9487728e882f6681ada6408440151acf) patches this so that if `EventDetection` is not found, the start time and duration are instead read from `Raw/Reads/`.  

Needs further testing to see if there are any downstream issues that this introduces.

**Comment by tillbaar** [comment]
After the recent commit, a new error occurs when I try to read my fast5 files:

`> myfast5 <- readFast5Summary(myfiles)`
`  Checking file validity`
`  Reading Channel Data`
`  Reading Raw Data`
`  Event data not found`
`  Error in H5Fopen(file) : HDF5. File accessability. Unable to open file.`

I have attachjed one of my fast5 files for refenrence.
[20171004__MN24694_sequencing_run_65683_read_10_ch_1_strand.fast5.gz](https://github.com/grimbough/IONiseR/files/1407272/20171004__MN24694_sequencing_run_65683_read_10_ch_1_strand.fast5.gz)

**Comment by grimbough** [comment]
I don't currently see this with that file e.g.

```
> readFast5Summary('/mnt/data/randomEncounters/Till_Baar/20171004__MN24694_sequencing_run_65683_read_10_ch_1_strand.fast5')
Checking file validity
Reading Channel Data
Reading Raw Data
Event data not found
Reading Template Data
Reading Template FASTQ
Done
Object of class: Fast5Summary
Contains information from:
  1 fast5 files
  |- 1 template strands
  |- 0 complement strands
  |- 0 full 2D reads
```
Presumbly `myfiles` is a vector of file paths.  Does it work for a single file for you?

**Comment by tillbaar** [comment]
Your suspicion was correct.
Loading of .fast5 files did work with a single file.

The error originated from those .fast5 files that were not successfully basecalled.
(Stored in the `fail/` and not in the `pass/` directory.)

When I restrict the vector of filepaths to the correctly basecalled files, loading of the data works without any errors or warnings.
